"""sprint1_schema

Revision ID: 30ddf788e9ad
Revises: 
Create Date: 2026-06-18 07:28:52.274376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ddf788e9ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamento_catalogo',
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('nombre_generico', sa.String(length=150), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=True),
    sa.Column('grupo_farmacologico', sa.String(length=100), nullable=True),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('concentracion', sa.String(length=50), nullable=True),
    sa.Column('via_administracion', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_medicamento')
    )
    op.create_index(op.f('ix_medicamento_catalogo_id_medicamento'), 'medicamento_catalogo', ['id_medicamento'], unique=False)
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('funcion_renal', sa.String(length=50), nullable=True),
    sa.Column('funcion_hepatica', sa.String(length=50), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_index(op.f('ix_paciente_ci'), 'paciente', ['ci'], unique=True)
    op.create_index(op.f('ix_paciente_id_paciente'), 'paciente', ['id_paciente'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('numero_licencia', sa.String(length=50), nullable=True),
    sa.Column('id_paciente_vinculado', sa.Integer(), nullable=True),
    sa.Column('requiere_cambio_password', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente_vinculado'], ['paciente.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('numero_licencia')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('diagnostico',
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('codigo_cie10', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_diagnostico')
    )
    op.create_index(op.f('ix_diagnostico_id_diagnostico'), 'diagnostico', ['id_diagnostico'], unique=False)
    op.create_table('historial_clinico',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo_evento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_clinico_id_historial'), 'historial_clinico', ['id_historial'], unique=False)
    op.create_table('receta',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_diagnostico', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('nivel_riesgo', sa.Integer(), nullable=True),
    sa.Column('resumen_validacion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('nivel_riesgo BETWEEN 0 AND 3', name='ck_receta_nivel_riesgo'),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnostico.id_diagnostico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_index(op.f('ix_receta_id_receta'), 'receta', ['id_receta'], unique=False)
    op.create_table('receta_medicamento',
    sa.Column('id_receta_med', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('dosis', sa.String(length=50), nullable=False),
    sa.Column('frecuencia', sa.String(length=50), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=False),
    sa.Column('via_administracion', sa.String(length=50), nullable=True),
    sa.Column('indicaciones', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamento_catalogo.id_medicamento'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id_receta'], ),
    sa.PrimaryKeyConstraint('id_receta_med')
    )
    op.create_index(op.f('ix_receta_medicamento_id_receta_med'), 'receta_medicamento', ['id_receta_med'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receta_medicamento_id_receta_med'), table_name='receta_medicamento')
    op.drop_table('receta_medicamento')
    op.drop_index(op.f('ix_receta_id_receta'), table_name='receta')
    op.drop_table('receta')
    op.drop_index(op.f('ix_historial_clinico_id_historial'), table_name='historial_clinico')
    op.drop_table('historial_clinico')
    op.drop_index(op.f('ix_diagnostico_id_diagnostico'), table_name='diagnostico')
    op.drop_table('diagnostico')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_paciente_id_paciente'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_ci'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_medicamento_catalogo_id_medicamento'), table_name='medicamento_catalogo')
    op.drop_table('medicamento_catalogo')
    # ### end Alembic commands ###
