"""sprint3_blockchain_dispensacion

Revision ID: 7f2554fa8818
Revises: d1551b61f305
Create Date: 2026-06-20 08:54:01.154014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2554fa8818'
down_revision: Union[str, Sequence[str], None] = 'd1551b61f305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispensacion',
    sa.Column('id_dispensacion', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('codigo_qr', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_dispensacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id_receta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_dispensacion'),
    sa.UniqueConstraint('codigo_qr')
    )
    op.create_index(op.f('ix_dispensacion_id_dispensacion'), 'dispensacion', ['id_dispensacion'], unique=False)
    op.create_table('trazabilidad_blockchain',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('hash_receta', sa.String(length=255), nullable=False),
    sa.Column('bloque_id', sa.String(length=255), nullable=True),
    sa.Column('direccion_contrato', sa.String(length=255), nullable=True),
    sa.Column('timestamp_blockchain', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario_firmante', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id_receta'], ),
    sa.ForeignKeyConstraint(['id_usuario_firmante'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_registro'),
    sa.UniqueConstraint('hash_receta')
    )
    op.create_index(op.f('ix_trazabilidad_blockchain_id_registro'), 'trazabilidad_blockchain', ['id_registro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trazabilidad_blockchain_id_registro'), table_name='trazabilidad_blockchain')
    op.drop_table('trazabilidad_blockchain')
    op.drop_index(op.f('ix_dispensacion_id_dispensacion'), table_name='dispensacion')
    op.drop_table('dispensacion')
    # ### end Alembic commands ###
