"""sprint2_audio_validacion_alerta

Revision ID: d1551b61f305
Revises: 30ddf788e9ad
Create Date: 2026-06-20 08:03:24.976649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1551b61f305'
down_revision: Union[str, Sequence[str], None] = '30ddf788e9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_clinico',
    sa.Column('id_audio', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('estado_procesamiento', sa.String(length=30), nullable=False),
    sa.Column('fecha_grabacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id_receta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_audio')
    )
    op.create_index(op.f('ix_audio_clinico_id_audio'), 'audio_clinico', ['id_audio'], unique=False)
    op.create_table('validacion_ia',
    sa.Column('id_validacion', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_audio', sa.Integer(), nullable=True),
    sa.Column('nivel_riesgo', sa.Integer(), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('interacciones', sa.Text(), nullable=True),
    sa.Column('contraindicaciones', sa.Text(), nullable=True),
    sa.Column('duplicidades', sa.Text(), nullable=True),
    sa.Column('errores_dosis', sa.Text(), nullable=True),
    sa.Column('coherencia_audio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('modelo_usado', sa.String(length=100), nullable=True),
    sa.Column('tiempo_respuesta_ms', sa.Integer(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('nivel_riesgo BETWEEN 0 AND 3', name='ck_validacion_nivel_riesgo'),
    sa.ForeignKeyConstraint(['id_audio'], ['audio_clinico.id_audio'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id_receta'], ),
    sa.PrimaryKeyConstraint('id_validacion')
    )
    op.create_index(op.f('ix_validacion_ia_id_validacion'), 'validacion_ia', ['id_validacion'], unique=False)
    op.create_table('alerta_clinica',
    sa.Column('id_alerta', sa.Integer(), nullable=False),
    sa.Column('id_validacion', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('nivel BETWEEN 0 AND 3', name='ck_alerta_nivel'),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id_receta'], ),
    sa.ForeignKeyConstraint(['id_validacion'], ['validacion_ia.id_validacion'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_index(op.f('ix_alerta_clinica_id_alerta'), 'alerta_clinica', ['id_alerta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerta_clinica_id_alerta'), table_name='alerta_clinica')
    op.drop_table('alerta_clinica')
    op.drop_index(op.f('ix_validacion_ia_id_validacion'), table_name='validacion_ia')
    op.drop_table('validacion_ia')
    op.drop_index(op.f('ix_audio_clinico_id_audio'), table_name='audio_clinico')
    op.drop_table('audio_clinico')
    # ### end Alembic commands ###
